# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.incrementLabel = QtWidgets.QLabel(self.centralwidget)
        self.incrementLabel.setGeometry(QtCore.QRect(40, 150, 91, 20))
        self.incrementLabel.setObjectName("incrementLabel")
        self.todatLabel = QtWidgets.QLabel(self.centralwidget)
        self.todatLabel.setGeometry(QtCore.QRect(40, 190, 91, 20))
        self.todatLabel.setObjectName("todatLabel")
        self.totalLabel = QtWidgets.QLabel(self.centralwidget)
        self.totalLabel.setGeometry(QtCore.QRect(41, 230, 91, 20))
        self.totalLabel.setObjectName("totalLabel")
        self.incrementButton = QtWidgets.QPushButton(self.centralwidget)
        self.incrementButton.setGeometry(QtCore.QRect(40, 280, 93, 51))
        self.incrementButton.setObjectName("incrementButton")
        self.todayButton = QtWidgets.QPushButton(self.centralwidget)
        self.todayButton.setGeometry(QtCore.QRect(170, 280, 93, 51))
        self.todayButton.setObjectName("todayButton")
        self.totalButton = QtWidgets.QPushButton(self.centralwidget)
        self.totalButton.setGeometry(QtCore.QRect(300, 280, 93, 51))
        self.totalButton.setObjectName("totalButton")
        self.incrementLine = QtWidgets.QLineEdit(self.centralwidget)
        self.incrementLine.setGeometry(QtCore.QRect(170, 150, 221, 21))
        self.incrementLine.setReadOnly(True)
        self.incrementLine.setObjectName("incrementLine")
        self.todayLine = QtWidgets.QLineEdit(self.centralwidget)
        self.todayLine.setGeometry(QtCore.QRect(170, 190, 221, 21))
        self.todayLine.setReadOnly(True)
        self.todayLine.setObjectName("todayLine")
        self.totalLine = QtWidgets.QLineEdit(self.centralwidget)
        self.totalLine.setGeometry(QtCore.QRect(170, 230, 221, 21))
        self.totalLine.setReadOnly(True)
        self.totalLine.setObjectName("totalLine")
        self.displayButton = QtWidgets.QPushButton(self.centralwidget)
        self.displayButton.setGeometry(QtCore.QRect(410, 180, 51, 51))
        self.displayButton.setObjectName("displayButton")
        self.databaseWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.databaseWidget.setGeometry(QtCore.QRect(570, 0, 631, 591))
        self.databaseWidget.setToolTipDuration(-1)
        self.databaseWidget.setObjectName("databaseWidget")
        self.databaseWidget.setColumnCount(0)
        self.databaseWidget.setRowCount(0)
        self.toolButton_2 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_2.setGeometry(QtCore.QRect(510, 60, 31, 31))
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_3.setGeometry(QtCore.QRect(510, 110, 31, 31))
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_4 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_4.setGeometry(QtCore.QRect(510, 10, 31, 31))
        self.toolButton_4.setObjectName("toolButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.incrementButton.clicked.connect(MainWindow.incrementButtonPushed)
        self.todayButton.clicked.connect(MainWindow.todayButtonPushed)
        self.totalButton.clicked.connect(MainWindow.totalButtonPushed)
        self.displayButton.clicked.connect(MainWindow.displayButtonPushed)
        self.toolButton_2.clicked.connect(MainWindow.removeButtonPushed)
        self.toolButton_3.clicked.connect(MainWindow.synchronizeButtonPushed)
        self.toolButton_4.clicked.connect(MainWindow.addWordsButtonPushed)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Main"))
        self.incrementLabel.setText(_translate("MainWindow", "Increment"))
        self.todatLabel.setText(_translate("MainWindow", "Today"))
        self.totalLabel.setText(_translate("MainWindow", "Total"))
        self.incrementButton.setText(_translate("MainWindow", "Increment"))
        self.todayButton.setText(_translate("MainWindow", "Today"))
        self.totalButton.setText(_translate("MainWindow", "Total"))
        self.displayButton.setText(_translate("MainWindow", "<<"))
        self.toolButton_2.setText(_translate("MainWindow", "-"))
        self.toolButton_3.setText(_translate("MainWindow", "SY"))
        self.toolButton_4.setText(_translate("MainWindow", "+"))

